stages:
  - verify
  - publish
  - deploy

variables:
  APP_NAME: ecom-sdk-javascript

chekmarks:
  stage: verify
  image: artifactory.raiffeisen.ru/automation-docker/checkmarx-cli:latest
  variables:
    CX_HIGH: "0"
    CX_MEDIUM: "0"
    CX_LOW: "0"
    CX_PRESET: "Checkmarx Default"
    CX_SERVER: "https://s-msk-p-chkmrx1.raiffeisen.ru/"
    CX_TEAM: "\\CxServer\\RAIFFEISEN\\Processing\\Acquiring"
  script:
    - /bin/sh /CxPlugin/cxcli/runCxConsole.sh AsyncScan -cxserver "$CX_SERVER" -cxuser "LDAP Authentication\\$ARTIFACTORY_LOGIN" -cxpassword "$ARTIFACTORY_PASSWORD" -projectname "\\CxServer\\RAIFFEISEN\\Processing\\Acquiring\\ecom-js-sdk" -preset "$CX_PRESET" -locationtype folder -locationpath $CI_PROJECT_DIR -sasthigh $CX_HIGH -sastmedium $CX_MEDIUM -sastlow $CX_LOW -reportxml $CI_PROJECT_DIR/results-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.xml -reportpdf $CI_PROJECT_DIR/results-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.pdf -comment "git $CI_COMMIT_REF_NAME@$CI_COMMIT_SHA" -v
  only:
    - merge_request

publish-npm:
  stage: publish
  image: artifactory.raiffeisen.ru/ecom-image-docker/npm:3
  script:
    - npm version patch --allow-same-version --force
    - npm publish --registry=registry.npmjs.org/:_authToken=$NPM_TOKEN
  only:
    - master

push:
  stage: deploy
  script:
    - git branch
    - git push https://$OPEN_SOURCE_GITHUB_LOGIN:$OPEN_SOURCE_GITHUB_PASSWORD@github.com/Raiffeisen-DGTL/ecom-front-js-sdk.git HEAD:master
  only:
    - master